services:
    db1:
        image: ${SERVER_IMAGE}
        ports:
            - "8091:8091"
        volumes:
            - ./logs:/opt/couchbase/var/lib/couchbase/logs/:rw
            - ./configure-cbs.sh:/entrypoint.sh
    logging:
        image: ${FLUENT_BIT_IMAGE}
        # Override the entrypoint to prevent auto-restart
        command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
        ports:
            - "2020:2020"
        depends_on:
            - db1
        volumes:
            - ./logs:/opt/couchbase/var/lib/couchbase/logs/:ro
            - ./fluent-bit.conf:/fluent-bit/config/fluent-bit.conf:ro
