version: "3"
networks:
    front:
    back:

services:
    db1:
        container_name: db1
        image: ${SERVER_IMAGE}
        ports:
            - "8091-8096:8091-8096"
            - "11210-11211:11210-11211"
        volumes:
            - log-volume:/opt/couchbase/var/lib/couchbase/logs/:rw
            - ./configure-cbs.sh:/entrypoint.sh
        networks:
            back:
                aliases:
                    - couchbase1.compose.local
    logging:
        container_name: logging
        image: ${FLUENT_BIT_IMAGE}
        ports:
            - "2020:2020"
        depends_on:
            - db1
            - loki
        environment:
            - COUCHBASE_LOGS=/opt/couchbase/var/lib/couchbase/logs
            - LOKI_HOST=loki
            - LOKI_PORT=3100
            # Send all logs to Loki
            - LOKI_MATCH=*
            # Only send audit log to standard output
            - STDOUT_MATCH=couchbase.log.audit
        volumes:
            - log-volume:/opt/couchbase/var/lib/couchbase/logs/:ro
        networks:
            - back
    loki:
        image: ${LOKI_IMAGE}
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - back

    # Default creds are admin:password
    grafana:
        image: ${GRAFANA_IMAGE}
        ports:
            - "3000:3000"
        networks:
            - front
            - back
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=password

volumes:
    log-volume:
    grafana_data:
