pipeline {
  agent {
    label 'ubuntu-18.04 && master'
  }

  environment {
    GOVERSION = '1.16.2'
    PATH = "${env.WORKSPACE}/go/bin:${PATH}"
  }

  stages {
    stage('Go Install') {
      steps {
        sh 'wget -q -O- https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz | tar xz'
      }
    }
    stage('Build code') {
      steps {
        sh 'make build'
      }
    }
    stage('Lint code') {
      steps {
        sh 'make lint'
      }
    }
    stage('Test packaging for build') {
      steps {
        sh 'make dist'
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
